"""
VulnOps Remediation Service
Creates Jira tickets for prioritized vulnerabilities,
triggers Ansible playbooks for automated patching,
and maintains full audit trail.
"""

import os
import json
import logging
import subprocess
from datetime import datetime
from typing import Optional

import psycopg2
import psycopg2.extras
import requests
from fastapi import FastAPI, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

DATABASE_URL = os.getenv("DATABASE_URL", "postgresql://vulnops:vulnops@postgres:5432/vulnops")
JIRA_URL = os.getenv("JIRA_URL", "")
JIRA_USER = os.getenv("JIRA_USER", "")
JIRA_TOKEN = os.getenv("JIRA_TOKEN", "")
JIRA_PROJECT = os.getenv("JIRA_PROJECT", "VULN")
ANSIBLE_PLAYBOOKS_DIR = os.getenv("ANSIBLE_PLAYBOOKS_DIR", "/playbooks")
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL", "")

app = FastAPI(title="VulnOps Remediation API", version="1.0.0")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])


def get_db():
    return psycopg2.connect(DATABASE_URL, cursor_factory=psycopg2.extras.RealDictCursor)


def create_jira_ticket(vuln: dict) -> Optional[str]:
    """Create a Jira ticket for the vulnerability. Returns ticket key or None."""
    if not all([JIRA_URL, JIRA_USER, JIRA_TOKEN]):
        ticket_key = f"VULN-{str(vuln['id'])[:8].upper()}"
        logger.info(f"Jira not configured — simulated ticket: {ticket_key}")
        return ticket_key

    ai_data = {}
    if vuln.get("ai_remediation"):
        try:
            ai_data = json.loads(vuln["ai_remediation"])
        except (json.JSONDecodeError, TypeError):
            pass

    steps = "\n".join(
        f"# {i+1}. {step}"
        for i, step in enumerate(ai_data.get("steps", ["Review and patch the package"]))
    )

    sla_str = ""
    if vuln.get("sla_deadline"):
        sla_str = f"*SLA Deadline:* {vuln['sla_deadline']}\n"

    description = f"""
h2. Vulnerability Details
*CVE:* {vuln.get('cve_id', 'N/A')}
*Severity:* {vuln.get('severity', 'N/A')}
*CVSS Score:* {vuln.get('cvss_score') or 'N/A'}
*EPSS Score:* {vuln.get('epss_score') or 'N/A'} (exploit probability)
*Affected Asset:* {vuln.get('asset', 'N/A')}
*Package:* {vuln.get('package', 'N/A')} {vuln.get('installed_version', '')}
*Fixed Version:* {vuln.get('fixed_version') or 'Not yet available'}
{sla_str}
h2. Description
{vuln.get('description', 'See NVD for details.')[:500]}

h2. AI Risk Assessment
{vuln.get('ai_rationale', 'Not yet assessed')}

h2. Remediation Steps
{steps}

h2. Compensating Controls
{ai_data.get('compensating_controls', 'Apply vendor guidance if patch unavailable.')}

h2. Estimated Effort
{ai_data.get('estimated_effort', 'Unknown')}

_Ticket auto-generated by VulnOps_
""".strip()

    priority_map = {"CRITICAL": "Highest", "HIGH": "High", "MEDIUM": "Medium", "LOW": "Low"}

    payload = {
        "fields": {
            "project": {"key": JIRA_PROJECT},
            "summary": f"[{vuln.get('severity')}] {vuln.get('cve_id')} on {vuln.get('asset')}",
            "description": description,
            "issuetype": {"name": "Bug"},
            "priority": {"name": priority_map.get(vuln.get("ai_risk_tier", "MEDIUM"), "Medium")},
            "labels": ["vulnerability", "vulnops", vuln.get("severity", "").lower()],
        }
    }

    try:
        resp = requests.post(
            f"{JIRA_URL}/rest/api/2/issue",
            json=payload,
            auth=(JIRA_USER, JIRA_TOKEN),
            headers={"Content-Type": "application/json"},
            timeout=15,
        )
        resp.raise_for_status()
        ticket_key = resp.json().get("key")
        logger.info(f"Created Jira ticket: {ticket_key}")
        return ticket_key
    except Exception as e:
        logger.error(f"Jira ticket creation failed: {e}")
        return None


def send_slack_alert(vuln: dict, ticket_key: str):
    """Send Slack notification for critical/high vulnerabilities."""
    if not SLACK_WEBHOOK_URL:
        return

    color = "#E24B4A" if vuln.get("severity") == "CRITICAL" else "#EF9F27"
    message = {
        "attachments": [{
            "color": color,
            "title": f"🚨 {vuln.get('severity')} Vulnerability: {vuln.get('cve_id')}",
            "fields": [
                {"title": "Asset", "value": vuln.get("asset", "N/A"), "short": True},
                {"title": "CVSS", "value": str(vuln.get("cvss_score") or "N/A"), "short": True},
                {"title": "EPSS", "value": f"{vuln.get('epss_score') or 0:.3f}", "short": True},
                {"title": "SLA Deadline", "value": str(vuln.get("sla_deadline", "N/A")), "short": True},
                {"title": "Jira Ticket", "value": ticket_key, "short": True},
            ],
            "footer": "VulnOps | Vulnerability Management Platform",
        }]
    }
    try:
        requests.post(SLACK_WEBHOOK_URL, json=message, timeout=10)
    except Exception as e:
        logger.warning(f"Slack alert failed: {e}")


def trigger_ansible_patch(vuln: dict) -> bool:
    """
    Trigger an Ansible playbook to patch the vulnerability.
    In production this would run against the actual host inventory.
    """
    playbook = os.path.join(ANSIBLE_PLAYBOOKS_DIR, "patch_package.yml")
    if not os.path.exists(playbook):
        logger.info(f"Ansible playbook not found at {playbook} — simulating run")
        return True

    cmd = [
        "ansible-playbook", playbook,
        "--extra-vars", json.dumps({
            "target_host": vuln.get("asset", "localhost"),
            "package_name": vuln.get("package", ""),
            "target_version": vuln.get("fixed_version", "latest"),
            "cve_id": vuln.get("cve_id", ""),
        }),
        "--tags", "patch",
    ]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if result.returncode == 0:
            logger.info(f"Ansible patch succeeded for {vuln.get('cve_id')}")
            return True
        else:
            logger.error(f"Ansible failed: {result.stderr}")
            return False
    except Exception as e:
        logger.error(f"Ansible execution error: {e}")
        return False


def process_prioritized_vulnerabilities():
    """Main loop: pick up prioritized vulns, create tickets, trigger patches."""
    conn = get_db()
    cur = conn.cursor()
    cur.execute("""
        SELECT * FROM vulnerabilities
        WHERE status = 'prioritized' AND jira_ticket IS NULL
        ORDER BY
            CASE ai_risk_tier
                WHEN 'CRITICAL' THEN 1 WHEN 'HIGH' THEN 2
                WHEN 'MEDIUM' THEN 3 ELSE 4
            END
        LIMIT 20
    """)
    rows = [dict(r) for r in cur.fetchall()]

    for vuln in rows:
        ticket_key = create_jira_ticket(vuln)
        if ticket_key:
            cur.execute("""
                UPDATE vulnerabilities SET
                    jira_ticket = %s,
                    status = 'ticketed',
                    updated_at = NOW()
                WHERE id = %s
            """, (ticket_key, vuln["id"]))
            cur.execute("""
                INSERT INTO audit_log (vuln_id, action, old_status, new_status, actor, notes)
                VALUES (%s, 'ticket_created', 'prioritized', 'ticketed', 'vulnops-bot', %s)
            """, (vuln["id"], f"Jira ticket {ticket_key} created"))
            conn.commit()

            if vuln.get("severity") in ("CRITICAL", "HIGH"):
                send_slack_alert(vuln, ticket_key)

            # Auto-patch if fixed version is available and severity is critical
            if vuln.get("fixed_version") and vuln.get("severity") == "CRITICAL":
                patched = trigger_ansible_patch(vuln)
                if patched:
                    cur.execute("""
                        UPDATE vulnerabilities SET status = 'remediated', remediated_at = NOW()
                        WHERE id = %s
                    """, (vuln["id"],))
                    cur.execute("""
                        INSERT INTO audit_log (vuln_id, action, old_status, new_status, actor, notes)
                        VALUES (%s, 'auto_patched', 'ticketed', 'remediated', 'ansible-bot', %s)
                    """, (vuln["id"], f"Auto-patched to {vuln.get('fixed_version')}"))
                    conn.commit()

    cur.close()
    conn.close()
    return len(rows)


@app.get("/health")
def health():
    return {"status": "ok", "service": "remediation"}


@app.post("/remediation/run")
def run_remediation(background_tasks: BackgroundTasks):
    background_tasks.add_task(process_prioritized_vulnerabilities)
    return {"message": "Remediation batch started"}


@app.get("/audit-log")
def get_audit_log(vuln_id: Optional[str] = None, limit: int = 100):
    conn = get_db()
    cur = conn.cursor()
    if vuln_id:
        cur.execute(
            "SELECT * FROM audit_log WHERE vuln_id = %s ORDER BY created_at DESC LIMIT %s",
            (vuln_id, limit)
        )
    else:
        cur.execute("SELECT * FROM audit_log ORDER BY created_at DESC LIMIT %s", (limit,))
    rows = [dict(r) for r in cur.fetchall()]
    cur.close()
    conn.close()
    return rows
